
[[plugins]]
repo= 'yuki-ycino/fzf-preview.vim'
depends='coc.nvim'
rev = 'release'
hook_post_update = '''
FzfPreviewInstall
'''

[[plugins]]
repo='jsfaint/coc-neoinclude'
depends=['coc.nvim','Shougo/neoinclude.vim']

[[plugins]]
depends=['coc.nvim', 'neco-vim']
repo='neoclide/coc-neco'
on_ft='vim'
hook_post_update = '''
try
  coc#util#install()
catch /.*/
echomsg "coc-neco failed"
endtry
'''

[[plugins]]
repo= 'neoclide/coc-snippets'
depends='coc.nvim'
hook_post_source = '''
try
    CocInstall coc-snippets
catch /.*/
  echomsg "coc-snippets failed"
endtry
'''

[[plugins]]
repo= 'neoclide/coc-highlight'
depends='coc.nvim'
hook_post_source = '''
try
    CocInstall coc-highlight
catch /.*/
    echomsg "CocInstall coc-highlight failed"
endtry
'''
