[[plugins]]
repo = 'mhinz/vim-startify'
on_cmd = 'Startify'
depends = 'vim-devicons'
hook_source='''
function! s:filter_header(lines) abort
let longest_line   = max(map(copy(a:lines), 'strwidth(v:val)'))
let centered_lines = map(copy(a:lines),
    \ 'repeat(" ", (&columns / 2) - (longest_line / 2)) . v:val')
return centered_lines
endfunction
let g:startify_custom_header = s:filter_header(startify#fortune#cowsay())
'''

[[plugins]]
repo= 'yuki-ycino/fzf-preview.vim'
depends='coc.nvim'
rev = 'release'
hook_post_update = '''
CocInstall coc-fzf-preview | FzfPreviewInstall
'''

[[plugins]]
repo='jsfaint/coc-neoinclude'
depends='coc.nvim'
hook_post_source = '''
CocInstall coc-neoinclude
'''

[[plugins]]
repo= 'neoclide/coc-snippets'
depends='coc.nvim'
hook_post_source = '''
CocInstall coc-snippets
'''

[[plugins]]
depends='coc.nvim'
repo= 'neoclide/coc-highlight'
hook_post_source = '''
CocInstall coc-highlight
'''

[[plugins]]
repo = 'neoclide/coc-neco'
depends = ['coc.nvim','neco-vim']
on_ft = 'vim'
hook_post_source = '''
CocInstall coc-neco
'''

[[plugins]]
repo= 'yuki-ycino/fzf-preview.vim'
depends='coc.nvim'
rev = 'release'
hook_post_update = '''
CocInstall coc-fzf-preview | FzfPreviewInstall
'''


[[plugins]]
repo='Maxattax97/coc-ccls'
build='yarn install --frozen-lockfile'
hook_post_source = '''
CocInstall coc-ccls
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
